name: Build
on: [fork]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: npm install -g @darabonba/cli

      - name: sample darabonba-Util install
        working-directory: ./sample
        run: dara install darabonba:Util -S
          
      - name: sdk darabonba-Util install
        working-directory: ./sdk
        run: dara install darabonba:Util -S
        
      - name: sample alibabacloud-OpenApiUtil install
        working-directory: ./sample
        run: dara install alibabacloud:OpenApiUtil -S

      - name: sdk alibabacloud-OpenApiUtil install
        working-directory: ./sdk
        run: dara install alibabacloud:OpenApiUtil -S
